name: Auto-merge main -> staging

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - staging

permissions:
  contents: read
  pull-requests: read

jobs:
  enable-automerge:
    # SÃ³ habilita automerge se o PR for main -> staging
    if: >
      github.event.pull_request.base.ref == 'staging' &&
      github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge for this PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT_AUTOMERGE }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          commit-title: 'chore: sync main -> staging'